
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectMVC.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    public int Id { get; set; }

    public Nullable<int> DocumentTypeId { get; set; }

    public string DocumentNumber { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string Surname { get; set; }

    public string SecondSurname { get; set; }

    public string Telephone { get; set; }

    public string Address { get; set; }

    public Nullable<int> CityId { get; set; }

    public int UserId { get; set; }



    public virtual Cities Cities { get; set; }

    public virtual DocumentTypes DocumentTypes { get; set; }

    public virtual Users Users { get; set; }

    public virtual Vehicles Vehicles { get; set; }

}

}
