

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectMVC.DAL.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ProjectMVCEntities : DbContext
{
    public ProjectMVCEntities()
        : base("name=ProjectMVCEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Artifacts> Artifacts { get; set; }

    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<Members> Members { get; set; }

    public virtual DbSet<Projects> Projects { get; set; }

    public virtual DbSet<Tenants> Tenants { get; set; }

    public virtual DbSet<UserProjects> UserProjects { get; set; }

    public virtual DbSet<Activities> Activities { get; set; }

    public virtual DbSet<Priorities> Priorities { get; set; }

    public virtual DbSet<States> States { get; set; }

    public virtual DbSet<Tasks> Tasks { get; set; }

    public virtual DbSet<AuthoritiesTransit> AuthoritiesTransit { get; set; }

    public virtual DbSet<Brands> Brands { get; set; }

    public virtual DbSet<Cities> Cities { get; set; }

    public virtual DbSet<ClassVehicle> ClassVehicle { get; set; }

    public virtual DbSet<Customer> Customer { get; set; }

    public virtual DbSet<DocumentTypes> DocumentTypes { get; set; }

    public virtual DbSet<Matches> Matches { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<Teams> Teams { get; set; }

    public virtual DbSet<TypeFuels> TypeFuels { get; set; }

    public virtual DbSet<TypeMaintenance> TypeMaintenance { get; set; }

    public virtual DbSet<TypeServices> TypeServices { get; set; }

    public virtual DbSet<TypeTires> TypeTires { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<VehicleFuels> VehicleFuels { get; set; }

    public virtual DbSet<VehicleGeneralInformation> VehicleGeneralInformation { get; set; }

    public virtual DbSet<VehicleMaintenance> VehicleMaintenance { get; set; }

    public virtual DbSet<VehiclePolicySOAT> VehiclePolicySOAT { get; set; }

    public virtual DbSet<Vehicles> Vehicles { get; set; }

    public virtual DbSet<VehicleTechnicalData> VehicleTechnicalData { get; set; }

}

}

