//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectMVCEntities2 : DbContext
    {
        public ProjectMVCEntities2()
            : base("name=ProjectMVCEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Artifact> Artifacts { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AuthoritiesTransit> AuthoritiesTransits { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ClassVehicle> ClassVehicles { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<TypeFuel> TypeFuels { get; set; }
        public virtual DbSet<TypeMaintenance> TypeMaintenances { get; set; }
        public virtual DbSet<TypeService> TypeServices { get; set; }
        public virtual DbSet<TypeTire> TypeTires { get; set; }
        public virtual DbSet<UserProject> UserProjects { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VehicleFuel> VehicleFuels { get; set; }
        public virtual DbSet<VehicleGeneralInformation> VehicleGeneralInformations { get; set; }
        public virtual DbSet<VehicleMaintenance> VehicleMaintenances { get; set; }
        public virtual DbSet<VehiclePolicySOAT> VehiclePolicySOATs { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleTechnicalData> VehicleTechnicalDatas { get; set; }
    }
}
