
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectMVC.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tasks
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Details { get; set; }

    public Nullable<System.DateTime> ExpirationDate { get; set; }

    public Nullable<bool> IsCompleted { get; set; }

    public Nullable<int> Effort { get; set; }

    public Nullable<int> RemainingWork { get; set; }

    public Nullable<int> StateId { get; set; }

    public Nullable<int> ActivityId { get; set; }

    public Nullable<int> PriorityId { get; set; }

    public Nullable<int> ProjectId { get; set; }



    public virtual Activities Activities { get; set; }

    public virtual Priorities Priorities { get; set; }

    public virtual Projects Projects { get; set; }

    public virtual States States { get; set; }

}

}
