
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectMVC.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserProjects
{

    public int Id { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public string UserId { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

    public virtual Projects Projects { get; set; }

}

}
