//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.VehicleFuels = new HashSet<VehicleFuel>();
            this.VehicleGeneralInformations = new HashSet<VehicleGeneralInformation>();
            this.VehicleMaintenances = new HashSet<VehicleMaintenance>();
            this.VehiclePolicySOATs = new HashSet<VehiclePolicySOAT>();
            this.VehicleTechnicalDatas = new HashSet<VehicleTechnicalData>();
        }
    
        public int C_ { get; set; }
        public string LicensePlate { get; set; }
        public string NroTransitLicense { get; set; }
        public Nullable<bool> StateVehicle { get; set; }
        public Nullable<int> TypeServiceId { get; set; }
        public Nullable<int> ClassVehicleId { get; set; }
        public string Image { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual ClassVehicle ClassVehicle { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TypeService TypeService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleFuel> VehicleFuels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleGeneralInformation> VehicleGeneralInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleMaintenance> VehicleMaintenances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiclePolicySOAT> VehiclePolicySOATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleTechnicalData> VehicleTechnicalDatas { get; set; }
    }
}
