
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectMVC.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Vehicles
{

    public int Id { get; set; }

    public string LicensePlate { get; set; }

    public string NroTransitLicense { get; set; }

    public Nullable<bool> StateVehicle { get; set; }

    public Nullable<int> TypeServiceId { get; set; }

    public Nullable<int> ClassVehicleId { get; set; }

    public string Image { get; set; }

    public Nullable<int> CustomerId { get; set; }



    public virtual ClassVehicle ClassVehicle { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual TypeServices TypeServices { get; set; }

    public virtual VehicleFuels VehicleFuels { get; set; }

    public virtual VehicleGeneralInformation VehicleGeneralInformation { get; set; }

    public virtual VehicleMaintenance VehicleMaintenance { get; set; }

    public virtual VehiclePolicySOAT VehiclePolicySOAT { get; set; }

    public virtual VehicleTechnicalData VehicleTechnicalData { get; set; }

}

}
