
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectMVC.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VehiclePolicySOAT
{

    public int Id { get; set; }

    public string PolicyNumber { get; set; }

    public Nullable<System.DateTime> ExpeditionDate { get; set; }

    public Nullable<System.DateTime> DateStartValidity { get; set; }

    public Nullable<System.DateTime> EndDateValidity { get; set; }

    public string SOATIssueEntity { get; set; }

    public Nullable<bool> State { get; set; }

    public Nullable<int> VehicleId { get; set; }



    public virtual Vehicles Vehicles { get; set; }

}

}
