
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectMVC.DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VehicleTechnicalData
{

    public int Id { get; set; }

    public Nullable<double> CapacityLoad { get; set; }

    public Nullable<int> PassengerCapacity { get; set; }

    public Nullable<double> GVWR { get; set; }

    public Nullable<int> CapacityPassengersSitting { get; set; }

    public Nullable<int> NumberAxes { get; set; }

    public Nullable<int> VehicleId { get; set; }



    public virtual Vehicles Vehicles { get; set; }

}

}
