//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMaintenance
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public Nullable<double> CurrentMileage { get; set; }
        public Nullable<System.DateTime> NextMaintenanceDate { get; set; }
        public Nullable<int> TypeMaintenanceId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> VehicleId { get; set; }
    
        public virtual TypeMaintenance TypeMaintenance { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
