//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleGeneralInformation
    {
        public int Id { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string Line { get; set; }
        public Nullable<int> Model { get; set; }
        public string Color { get; set; }
        public string SerialNumber { get; set; }
        public string EngineNumber { get; set; }
        public string ChassisNumber { get; set; }
        public string VIN { get; set; }
        public Nullable<int> Cylinder { get; set; }
        public string TypeBody { get; set; }
        public Nullable<int> TypeFuelId { get; set; }
        public Nullable<System.DateTime> InitialEnrollmentDate { get; set; }
        public Nullable<int> NroDoors { get; set; }
        public Nullable<int> TypeTireId { get; set; }
        public Nullable<int> AuthoritiesTransitId { get; set; }
        public Nullable<int> VehicleId { get; set; }
    
        public virtual AuthoritiesTransit AuthoritiesTransit { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual TypeFuel TypeFuel { get; set; }
        public virtual TypeTire TypeTire { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
